# Generated by Django 5.1 on 2024-09-29 09:13

import medicine_reminder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(default=medicine_reminder.models.get_default_date),
        ),
    ]
