# Generated by Django 5.1 on 2024-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminder', '0002_alter_reminder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindertime',
            name='unit',
            field=models.CharField(default='pills', max_length=50),
            preserve_default=False,
        ),
    ]
