# Generated by Django 5.1 on 2024-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reason_for_medication',
            field=models.TextField(default='for sickness'),
            preserve_default=False,
        ),
    ]
