# Generated by Django 5.1 on 2024-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritinganalysistable',
            name='prescription_name',
            field=models.CharField(default='prescription test', help_text='Name of the prescription', max_length=100),
            preserve_default=False,
        ),
    ]
